// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyofvafovpwrrusqljrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b2Z2YWZvdnB3cnJ1c3FsanJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDY0MzAsImV4cCI6MjA2OTMyMjQzMH0.Aj7XrAyTetNqJ3sZJBuVfXZNy8H1paE3N3bA7ag_Q68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});